// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMJkTTpHGOR4MJx0kynYeF_TT1q4b2yyw',
    appId: '1:462928806998:web:35d6ac07f47509acf6e7f7',
    messagingSenderId: '462928806998',
    projectId: 'lab08-90955',
    authDomain: 'lab08-90955.firebaseapp.com',
    storageBucket: 'lab08-90955.appspot.com',
    measurementId: 'G-EDWXLWJ2TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4FgzGu8Gf2O_Kuyt6uh90ZCk6CK2XqJI',
    appId: '1:462928806998:android:631d9df1533022d0f6e7f7',
    messagingSenderId: '462928806998',
    projectId: 'lab08-90955',
    storageBucket: 'lab08-90955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYqzlLZcfEJPFk1R6M2wYL8pqS2EtDg1I',
    appId: '1:462928806998:ios:759a17b79897a362f6e7f7',
    messagingSenderId: '462928806998',
    projectId: 'lab08-90955',
    storageBucket: 'lab08-90955.appspot.com',
    iosClientId:
        '462928806998-271shf0u96ptvp5vs4tkopaa4u70eoto.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYqzlLZcfEJPFk1R6M2wYL8pqS2EtDg1I',
    appId: '1:462928806998:ios:759a17b79897a362f6e7f7',
    messagingSenderId: '462928806998',
    projectId: 'lab08-90955',
    storageBucket: 'lab08-90955.appspot.com',
    iosClientId:
        '462928806998-271shf0u96ptvp5vs4tkopaa4u70eoto.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );
}
